### ISSUE TITLE
[Request] Adding Threejs bufferGeometry to replicad object converter in replicad-threejs-helper

### ISSUE THREAD

**Issue by abelops** [sgenoud/replicad#152]
I am integrating Replicad to existing Threejs project and I wanted to be able to use Replicad fillet and chamfer operations on a buffer geometry from threejs. It would be helpful to have this feature in Replicad just like there is a feature to convert replicad to three js in replicad-threejs-helper.

**Comment by sgenoud** [comment]
There is an important issue with your proposition. In order to get a Threejs buffer geometries from a replicad object, you need to mesh it. Unfortunaly the reverse operation from a mesh (buffer geometry) to a replicad object is a non trivial operation. 

While I would love to offer something in that spirit, this is not something I will tackle soon, so I close this issue (and might post on it if / when something like that is implemented).
