### ISSUE TITLE
Can't fuse a circle on the edge of another circle?

### ISSUE THREAD

**Issue by lf94** [sgenoud/replicad#36]
![1656378390](https://user-images.githubusercontent.com/547923/176065060-ccfef934-7643-4da6-a8a5-caed686590de.png)

Basically I'm trying to lay one circle on the edge of another and fuse them, but I get this error - any ideas?

```js
const main = ({ drawCircle, Plane }) => {
  const top  = drawCircle(44.0 / 2).sketchOnPlane(new Plane("XY")).extrude(3.0);
  const base = drawCircle(38.0 / 2).sketchOnPlane(new Plane("XY"))
    .loftWith(
      drawCircle(37.0 / 2)
      .fuse(drawCircle(3.0).translate([37.0 / 2 - 1.5, 0]))
      .sketchOnPlane(new Plane([0, 0, -10.0]))
    );
  const baseWithTop = top.fuse(base);
  const withCut = baseWithTop.cut(
    drawCircle(38.0 / 2 - 2.0).sketchOnPlane(new Plane([0, 0, -10.0])).extrude(13.0)
  );
  return [withCut];
};

```

**Comment by sgenoud** [comment]
The problem was with the translation - you need to pass to variables instead of a point - I should improve a bit on the error message which was misleading.

Also I am not 100% sure that you use the `Plane` constructor as you want to. I would advise you to to use the `makePlane` helper function - it takes as first argument the direction of the plane (as either its normal or a named plane `XZ` for instance) and as second argument the origin (i.e. the point which will be [0, 0] in the plane.). In the case of a named plane you can also pass just a number - it translate the plane along its normal. For instance makePlane("XZ", 5) will be the plane parallel to [0, 1, 0] which goes through [0, 5, 0].

Note that you can also now easily more around your planes to make the same plane you could `makePlane("XZ").translateY(5)`.

**Comment by raydeleu** [comment]
Another approach to model this shape could have been a revolve of the cross-section? This way you could avoid booleans which require more calculations.

**Comment by sgenoud** [comment]
> Another approach to model this shape could have been a revolve of the cross-section? This way you could avoid booleans which require more calculations.

Part of the advantage of 2D boolean operations is that they should be faster than the 3D ones (this is an hypothesis, I have not tested it to be honest). So, in theory the approach of doing boolean stuff in 2D and then extruding should be the most efficient way of building things.

**Comment by raydeleu** [comment]
Something else that came to my mind: the value of the Replicad concept is that a user can take functions, prepared by a different user to enhance his/her model. The "grip" idea used in this model has certain elements in it that - when generalized - are very useful to other users. For example, the function to create a radial array is interesting and can be used for all kinds of patterns.  Another is the idea to create a small protrusion to create a tight fit. 

In this example I would think that the solution envisaged by @lf94 using lofts would already be more generally applicable. It would also work on rectangular plugs, not only circular ones.  I assume that it would also solve the difficult calculation of the rotation angle for the grip-cylinders.  And using a standard loop instead of a mapping function to create a circular array where you can adapt the number of grips would be wider applicable and easier from a user perspective.  

The questions then are: 

* how we can persuade a user to create a separate function instead of a tailor-made solution,  
* how can we make the function more understandable,  
* what are guidelines to make a function more generic, so applicable to a wider range of models
* when a user has built such a useful function, how is this visible to other users of the library. Would it be possible to create something like a search tool where you type "array" or "grip" and you are lead to a boilerplate for a function to create this?
